# Generated by Django 4.1.5 on 2023-03-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_upvote_downvote_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.answer'),
        ),
    ]
