# Generated by Django 4.1.5 on 2023-03-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_tag_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
